server:
  port: 8888

# ÅäÖÃÎÄ¼şÎ»ÖÃ
spring:
  cloud:
    config:
      enabled: true
      server:
        bootstrap: true
        git:
          uri: https://github.com/fooololo/mamahao-microservice
          search-paths: [settings-repo]
#          basedir: settings-repo

